DROP Trigger patient_tr;
DROP Sequence patient_seq;
DROP Table patient CASCADE CONSTRAINTS;

CREATE TABLE patient (
  ID integer PRIMARY KEY,
  SVNR integer NULL,
  ADRESSE varchar2(255) NULL,
  GEBURTSDATUM date,
  GESCHLECHT varchar2(255),
  VORNAME varchar2(255),
  NACHNAME varchar2(255),
  KRANKENKASSE varchar2(255)
);

CREATE SEQUENCE patient_seq START WITH 1;

CREATE OR REPLACE TRIGGER patient_tr 
BEFORE INSERT ON patient 
FOR EACH ROW
BEGIN
  SELECT patient_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

INSERT INTO patient (SVNR, ADRESSE, GEBURTSDATUM, GESCHLECHT, VORNAME, NACHNAME, KRANKENKASSE) VALUES (1234, '1050 Wien, Musterstraße 1', TO_DATE('1990-02-01', 'YYYY-MM-DD'), 'MAENNLICH', 'Max', 'Mayer', 'BVA');
INSERT INTO patient (SVNR, ADRESSE, GEBURTSDATUM, GESCHLECHT, VORNAME, NACHNAME, KRANKENKASSE) VALUES (2345, '1050 Wien, Sauergasse 2', TO_DATE('1991-03-02', 'YYYY-MM-DD'), 'WEIBLICH', 'Susanne', 'Schmidt', 'WGKK');
INSERT INTO patient (SVNR, ADRESSE, GEBURTSDATUM, GESCHLECHT, VORNAME, NACHNAME, KRANKENKASSE) VALUES (3456, '1050 Wien, Hauptstraße 23', TO_DATE('1971-03-23', 'YYYY-MM-DD'), 'WEIBLICH', 'Helga', 'Lindner', 'NGKK');
